### ISSUE TITLE
Error occured while executing command (my command was /ba create kit soldier): Configuration does not accept objects of type class [B

### ISSUE THREAD

**Issue by Blackshadow25565** [mrdarcychen/BlockyArena#16]
UP!!! I'm using minecraft server sponge 1.12.2. Client and server haven't crashed

**Comment by Blackshadow25565** [comment]
Ah I forgotten!!! I tried to create a kit with mod items. Can be the problem?

**Comment by mrdarcychen** [comment]
Hi @Blackshadow25565 ,
Can you please send me the full error message appeared in the console? Mods item should be fine since version 0.4.1. Thanks:)

**Comment by mrdarcychen** [comment]
The solution is described as opening the game in a single player world first.
