### ISSUE TITLE
Kit Manager guesses Kits after Server Restart

### ISSUE THREAD

**Issue by Zocker9000** [mrdarcychen/BlockyArena#27]
After every Restart of my Server my kits are not available.

They´re still in the Kits folder but the Kit Manager doesnt recognize them. 
I just get the Message : Kit XXX doesn´t exist.

**Comment by mrdarcychen** [comment]
Please provide the console log around the incident.

**Comment by mrdarcychen** [comment]
This issue is now closed after one month of inactivity. Feel free to reopen it if the problem arises.
