### ISSUE TITLE
Future suggestions

### ISSUE THREAD

**Issue by oblx** [mrdarcychen/BlockyArena#3]
Hi,

@Keuterio from spongeforum here, I will write here my suggestion for your plugin as I am also making a similare stuff but not with java. Our ideas might help each other :)

Take care and don't forget to release on Ore, there is no name issue there !

**Comment by mrdarcychen** [comment]
Hi Keuterio,
I'm more than happy to hear your suggestions and share my ideas with you 😄. May I also follow up your current similar project?
I've just learned about Ore and it seems like a great official place to release my stuff. Thank you so much for keeping me updated 😃

**Comment by oblx** [comment]
Hi, sorry for late reply !
My project is similar in features but it's not java related as I am really lacking some skills there. It's royalcraft.fr, a server based on pushing players to discover the world and interact in an alternative way but always without mod.
I will surely share my ideas with you when I work back on /duel :)
